config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/home', to: 'pages#home'
  
  resources :generic_names do
    resources :reviewgenerics , only: [:create, :edit, :update, :destroy]
  end
  resources :medicaments do
    resources :reviewmeds , only: [:create, :edit, :update, :destroy]
  end
  resources :groups
  resources :subgroups
  resources :substitutions
  resources :generic_names
  resources :medicaments
  resources :producers
  resources :users
  resources :abouts , only: [:index]
  resources :reviews , only: [:index]
  
  get '/login', to: 'logins#new'
    post '/login', to: 'logins#create'
    get '/logout', to: 'logins#destroy'
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :subgroups, dependent: :destroy
  
  validates :ime_grupa, presence: true, length: {minumum: 5, maximum: 100}
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController 
    before_action :require_admin, only: [:edit, :update]
    
    def index
        @groups = Group.all.paginate(page: params[:page], per_page: 6)
    end
    
    def new
      @group = Group.new
    end
    
    def create
        @group = Group.new(group_params)
        if @group.save
          flash[:success]="Групата е успешно креирана."
          redirect_to groups_path
        else
          render :new
        end
    end
    
    def show
      @group = Group.find(params[:id])
      @subgroups = @group.subgroups
    end
    
    def edit
        @group=Group.find(params[:id])
    end
    
    def update
        @group=Group.find(params[:id])
        if @group.update(group_params)
            flash[:success] = "Групата е успешно изменета."
            redirect_to groups_path
        else
            render :edit
        end
    end
    
    def destroy
      @group=Group.find(params[:id])
      @group.destroy
      flash[:success] = "Групата е избришана."
      redirect_to groups_path
    end
    
    private
      def group_params
        params.require(:group).permit(:ime_grupa, :subgroup_id, :medicament_id)
      end
      
      def require_admin
        if current_user.admin != true
          flash[:danger] = "Промена може да направи само администратор"
          redirect_to groups_path
        end
      end
    
end

app/views/groups/edit.html.erb
<%= render 'shared/page_title', title: "Измени група" %> 
<%= render 'shared/errors', obj: @group %>

<div class="row">
    <div class="well col-md-10 col-md-offset-2">
        <%= form_for(@group, html: { multipart: true }) do |f| %>
        <%= f.label :Име_на_група %>
        <%= f.text_field :ime_grupa %>
        
        <%= f.submit 'Измени', class: "btn btn-success" %>
        <% end %>
    </div>
</div>

app/views/groups/index.html.erb
<%= render 'shared/page_title', title: "Сите групи на лекови" %>

<%= will_paginate %>
<% @groups.each do |group| %>
    <div class="row">
        <div class="col-lg-12 well">
            <section class="chef_info center">
               <h3> <%= link_to group.ime_grupa, group_path(group) %></h3>
            </section>
        </div>
    </div>
    <hr/>
<% end %>
<%= will_paginate %>

app/views/groups/new.html.erb
<%= render 'shared/page_title', title: "Додај нова група" %> 
<%= render 'shared/errors', obj: @group %>

<div class="row">
    <div class="well col-md-8 col-md-offset-2">
        <%= form_for @group do |f| %>
        <%= f.label :"Име на група:" %>
        <%= f.text_field :ime_grupa, :size => "40" %>
        </br></br>
        <%= f.submit 'Креирај', class: "btn btn-success pull-right" %>
        <% end %>
    </div>
</div>

app/views/groups/show.html.erb
<%= render 'shared/page_title', title: "Групи" %>
        
        <div class="col-lg-12 well">
            <section class="group_info center">
                <strong> <h3><%= link_to @group.ime_grupa, group_path(@group) %></h3> </strong>
                
            </section>
            </br>
            <h4><strong><u>Подгрупи од оваа група се:</u></strong></h4>
            <% @subgroups.each do |subgroup| %>
                <div class="col-lg-10 offset-2 well">
                    <h4><%= link_to subgroup.ime_podgrupa, subgroup_path(subgroup) %></h4>
                </div>
            <% end %>
            
        </div>
        <% if logged_in? && (current_user.admin) %>
            <div class="col-md-12 well">
                <button class="btn pull-left"><%= link_to "Додај нова подгрупа", new_subgroup_path %></button>
                <button class="btn pull-right btn-danger"><%= link_to "Избриши група", @group, method: :delete, data: {confirm: "Дали сте сигурни дека сакате да ја избришете групата?"} %></button>
                <button class="btn pull-right"><%= link_to "Измени", edit_group_path(@group.id) %></button>
            </div>
        <% end %>
        
        
    <hr/>