config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/home', to: 'pages#home'
  
  resources :generic_names do
    resources :reviewgenerics , only: [:create, :edit, :update, :destroy]
  end
  resources :medicaments do
    resources :reviewmeds , only: [:create, :edit, :update, :destroy]
  end
  resources :groups
  resources :subgroups
  resources :substitutions
  resources :generic_names
  resources :medicaments
  resources :producers
  resources :users
  resources :abouts , only: [:index]
  resources :reviews , only: [:index]
  
  get '/login', to: 'logins#new'
    post '/login', to: 'logins#create'
    get '/logout', to: 'logins#destroy'
end

app/models/subgroup.rb
class Subgroup < ActiveRecord::Base
  belongs_to :group
  has_many :substitutions, dependent: :destroy
  
  validates :ime_podgrupa, presence: true
  validates :group_id, presence: true
end

app/controllers/subgroups_controller.rb
class SubgroupsController < ApplicationController
    before_action :require_admin, only: [:edit, :update]
    
    def index
        @subgroups = Subgroup.all.paginate(page: params[:page], per_page: 6)
    end
    
    def show
        @subgroup = Subgroup.find(params[:id])
        @substitutions = @subgroup.substitutions
    end
    
    def new
        @subgroup = Subgroup.new
        @groups= Group.all
    end
    
    def create
        @subgroup = Subgroup.new(subgroup_params)
        if @subgroup.save
            flash[:success] = "Подгрупата е успешно креирана"
            redirect_to subgroups_path
        else
            render :new
        end
    end
    
    def edit
        @subgroup=Subgroup.find(params[:id])
    end
    
    def update
        @subgroup=Subgroup.find(params[:id])
        if @subgroup.update(subgroup_params)
            flash[:success] = "Подгрупата е успешно изменета."
            redirect_to subgroup_path(@subgroup)
        else
            render :edit
        end
    end
    
    def destroy
        @subgroup=Subgroup.find(params[:id])
        @subgroup.destroy
        flash[:success] = "Подгрупата е избришана."
         redirect_to subgroups_path
    end
    
    private
    
    def subgroup_params
        params.require(:subgroup).permit(:ime_podgrupa, :group_id)
    end
    
    def require_admin
      if current_user.admin != true
        flash[:danger] = "Промена може да направи само администратор"
        redirect_to subgroups_path
      end
    end
    
end

app/views/subgroups/edit.html.erb
<%= render 'shared/page_title', title: "Измени подгрупа" %> 
<%= render 'shared/errors', obj: @subgroup %>

<div class="row">
    <div class="well col-md-10 col-md-offset-2">
        <%= form_for(@subgroup, html: { multipart: true }) do |f| %>
        <%= f.label :Име_на_подгрупа %>
        <%= f.text_field :ime_podgrupa %>
        
        </br>
        
        <strong>Група:</strong>
        
        <%= f.collection_select(:group_id, Group.all, :id, :ime_grupa) %>
        
        <%= f.submit 'Измени', class: "btn btn-success" %>
        <% end %>
    </div>
</div>

app/views/subgroups/index.html.erb
<%= render 'shared/page_title', title: "Сите подгрупи" %>

<%= will_paginate %>
<% @subgroups.each do |subgroup| %>
    <div class="row">
        
        <div class="col-lg-12 well">
            <section class="chef_info center">
                <h3><%= link_to subgroup.ime_podgrupa, subgroup_path(subgroup) %></h3>
                <h4> е подгрупа од група <%= subgroup.group.ime_grupa  %> </h4>
                
            </section>
        </div>
        
    </div>
    <hr/>
<% end %>
<%= will_paginate %>

app/views/subgroups/new.html.erb
<%= render 'shared/page_title', title: "Додај нова подгрупа" %> 
<%= render 'shared/errors', obj: @subgroup %>

<div class="row">
    <div class="well col-md-8 col-md-offset-2">
        <%= form_for @subgroup do |f| %>
        <%= f.label :"Име на подгрупа:" %>
        <%= f.text_field :ime_podgrupa, :size => "40" %>
        
        </br></br>
        
        <strong>Група:</strong>
        
        <%= f.collection_select(:group_id, Group.all, :id, :ime_grupa, {:include_blank => ''}) %>

        </br></br>
        <%= f.submit 'Креирај', class: "btn btn-success pull-right" %>
        <% end %>
    </div>
</div>

app/views/subgroups/show.html.erb
<%= render 'shared/page_title', title: "Подгрупи" %>
        
        <div class="col-lg-12 well">
            <section class="group_info center">
                <h3><%= link_to @subgroup.ime_podgrupa, subgroup_path(@subgroup) %></h3>
            </section>
            </br>
            <% if @substitutions.any? %>
                <h4><u>Подгрупата се дели на:</u></h4>
                <% @substitutions.each do |substitution| %>
                    <div class="col-lg-10 offset-2 well">
                        <h4><%= link_to substitution.ime_podelba, substitution_path(substitution) %></h4>
                    </div>
                <% end %>
            <% else %>
                <h4>Оваа подгрупа не е сеуште доработена.</h4>
            <% end %>
        </div>
        <% if logged_in? && (current_user.admin) %>
            <div class="col-lg-12 well">
                <button class="btn pull-left"><%= link_to "Додај нова поделба", new_substitution_path %></button>
                <button class="btn pull-right btn-danger"><%= link_to "Избриши група", @subgroup, method: :delete, data: {confirm: "Дали сте сигурни дека сакате да ја избришете подгрупата?"} %></button>
                <button class="btn pull-right"><%= link_to "Измени", edit_subgroup_path(@subgroup.id) %></button>
            </div>
        <% end %>
    <hr/>