config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/home', to: 'pages#home'
  
  resources :generic_names do
    resources :reviewgenerics , only: [:create, :edit, :update, :destroy]
  end
  resources :medicaments do
    resources :reviewmeds , only: [:create, :edit, :update, :destroy]
  end
  resources :groups
  resources :subgroups
  resources :substitutions
  resources :generic_names
  resources :medicaments
  resources :producers
  resources :users
  resources :abouts , only: [:index]
  resources :reviews , only: [:index]
  
  get '/login', to: 'logins#new'
    post '/login', to: 'logins#create'
    get '/logout', to: 'logins#destroy'
end

app/models/producer.rb
class Producer < ActiveRecord::Base
  has_many :medicaments, dependent: :destroy
  
  validates :ime_proizvoditel, presence: true
  validates :poteklo, presence: true
  mount_uploader :picture, PictureUploader
end

app/controllers/producers_controller.rb
class ProducersController < ApplicationController 
  before_action :require_admin, only: [:edit, :update]
    
    def index
        @producers = Producer.all.paginate(page: params[:page], per_page: 6)
    end
    
    def new
      @producer = Producer.new
    end
    
    def create
        @producer = Producer.new(producer_params)
        if @producer.save
          flash[:success]="Производителот е успешно креиран."
          redirect_to producers_path
        else
          render :new
        end
    end
    
    def show
      @producer = Producer.find(params[:id])
      @medicaments = @producer.medicaments.all
    end
    
    def edit
        @producer=Producer.find(params[:id])
    end
    
    def update
        @producer=Producer.find(params[:id])
        if @producer.update(producer_params)
            flash[:success] = "Производителот е успешно изменет."
            redirect_to producers_path
        else
            render :edit
        end
    end
    
    def destroy
      @producer=Producer.find(params[:id])
      @producer.destroy
      flash[:success] = "Групата е избришана."
      redirect_to producers_path
    end
    
    private
      def producer_params
        params.require(:producer).permit(:ime_proizvoditel, :poteklo, :picture, :website)
      end
    
      def require_admin
        if current_user.admin != true
          flash[:danger] = "Промена може да направи само администратор"
          redirect_to producers_path
        end
      end
end

app/views/producers/edit.html.erb
<%= render 'shared/page_title', title: "Измени група" %> 
<%= render 'shared/errors', obj: @producer %>

<div class="row">
    <div class="well col-md-10 col-md-offset-2">
        <%= form_for(@producer, html: { multipart: true }) do |f| %>
        <%= f.label :"Име на производител:" %>
        <%= f.text_field :ime_proizvoditel %>
        </br></br>
        <%= f.label :"Потекло:" %>
        <%= f.text_field :poteklo %>
        </br></br>
        <%= f.label :"Веб сајт:" %>
        <%= f.text_field :website, :size => "40" %>
        </br></br>
        <span class="picture">
            <%= f.file_field :picture, accept: 'image/jpeg, image/gif, image/png, image/jpg' %>
        </span>
        </br></br>
        
        <%= f.submit 'Измени', class: "btn btn-success" %>
        <% end %>
    </div>
</div>

<script type = "text/javascript">
  $('#producer_picture').bind('change', function() {
    size_in_megabytes=this.files[0].size/1024/1024;
    if (size_in_megabytes>5)
    {
      alert('Максималната големина на слика е 5MB. Ве молиме одберете помала слика.');
    }
  });
</script> 

app/views/producers/index.html.erb
<%= render 'shared/page_title', title: "Сите производители" %>

<%= will_paginate %>
<% @producers.each do |prod| %>
    <div class="row">
        <div class="col-md-4">
          <%= image_tag(prod.picture.url, size: "250x150", class: "gravatar") if prod.picture? %>
        </div>
        <div class="col-lg-8 well">
            <section class="chef_info center">
               <h3> <%= link_to prod.ime_proizvoditel, producer_path(prod) %></h3>
            </section>
        </div>
        
    </div>
    <hr/>
<% end %>
<%= will_paginate %>

app/views/producers/new.html.erb
<%= render 'shared/page_title', title: "Додај нов производител" %> 
<%= render 'shared/errors', obj: @producer %>

<div class="row">
    <div class="well col-md-8 col-md-offset-2">
        <%= form_for @producer do |f| %>
        <%= f.label :"Име на производител:" %>
        <%= f.text_field :ime_proizvoditel, :size => "40" %>
        </br></br>
        <%= f.label :"Потекло:" %>
        <%= f.text_field :poteklo, :size => "40" %>
        </br></br>
        <%= f.label :"Веб сајт:" %>
        <%= f.text_field :website, :size => "40" %>
        </br></br>
        <span class="picture">
            <%= f.file_field :picture, accept: 'image/jpeg, image/gif, image/png' %>
        </span>
        </br></br>
        <%= f.submit 'Креирај', class: "btn btn-success pull-right" %>
        <% end %>
    </div>
</div>

<script type = "text/javascript">
  $('#producer_picture').bind('change', function() {
    size_in_megabytes=this.files[0].size/1024/1024;
    if (size_in_megabytes>5)
    {
      alert('Максималната големина на слика е 5MB. Ве молиме одберете помала слика.');
    }
  });
</script> 

app/views/producers/show.html.erb
<%= render 'shared/page_title', title: "Производител" %>
        
        <div class="col-lg-12 well">
            <section class="group_info center">
                <div class="show_producer">
                  <%= image_tag(@producer.picture.url, class:"gravatar") if @producer.picture? %>
                </div>
                <strong> <h3><u></u>Име на производител:</u> <%= @producer.ime_proizvoditel %></h3> </strong>
                <h4>Потекло: <%= @producer.poteklo %></h4>
                <% if @producer.website? %>
                    <h4>Веб сајт: <%= link_to @producer.website, url_for(@producer.website) %></h4>
                <% end %>
            </section>
            </br>
            <% if @medicaments.any? %>
                <h4><u>Лекови кои ги произведува:</u></h4>
                <% @medicaments.each do |med| %>
                    <div class="col-lg-10 offset-2 well">
                        <h4><%= link_to med.ime_lek, medicament_path(med) %></h4>
                        
                    </div>
                <% end %>
            <% else %>
                <h4>Овој производител нема регистрирани лекови во Република Македонија.</h4>
            <% end %>
        </div>
        <% if logged_in? && (current_user.admin) %>
            <div class="col-md-12 well">
                <button class="btn pull-left"><%= link_to "Додај нов производител", new_producer_path %></button>
                <button class="btn pull-left"><%= link_to "Додај нов лек", new_medicament_path %></button>
                <button class="btn pull-right btn-danger"><%= link_to "Избриши производител", @producer, method: :delete, data: {confirm: "Дали сте сигурни дека сакате да го избришете овој производител??"} %></button>
                <button class="btn pull-right"><%= link_to "Измени", edit_producer_path(@producer.id) %></button>
            </div>
        <% end %>
        
    <hr/>