config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/home', to: 'pages#home'
  
  resources :generic_names do
    resources :reviewgenerics , only: [:create, :edit, :update, :destroy]
  end
  resources :medicaments do
    resources :reviewmeds , only: [:create, :edit, :update, :destroy]
  end
  resources :groups
  resources :subgroups
  resources :substitutions
  resources :generic_names
  resources :medicaments
  resources :producers
  resources :users
  resources :abouts , only: [:index]
  resources :reviews , only: [:index]
  
  get '/login', to: 'logins#new'
    post '/login', to: 'logins#create'
    get '/logout', to: 'logins#destroy'
end

app/models/medicament.rb
class Medicament < ActiveRecord::Base
    belongs_to :producer
    belongs_to :generic_name
    has_many :reviewmeds
    
    validates :ime_lek, presence: true
    validates :generic_name_id, presence: true
    validates :producer_id, presence: true
end

app/controllers/medicaments_controller.rb
class MedicamentsController < ApplicationController
    before_action :require_admin, only: [:edit, :update]
    
    def index
        @medicaments = Medicament.all.paginate(page: params[:page], per_page: 6)
    end
    
    def show
        @medicament = Medicament.find(params[:id])
        @commentt = Reviewmed.new
        @kommeds = Medicament.find(params[:id]).reviewmeds
    end
    
    def new
        @medicament = Medicament.new
    end
    
    def create
        @medicament = Medicament.new(medicament_params)
        if @medicament.save
            flash[:success] = "Лекот е успешно креиран."
            redirect_to medicaments_path
        else
            render :new
        end
    end
    
    def edit
        @medicament=Medicament.find(params[:id])
    end
    
    def update
        @medicament=Medicament.find(params[:id])
        if @medicament.update(medicament_params)
            flash[:success] = "Лекот е успешно изменет."
            redirect_to medicament_path(@medicament)
        else
            render :edit
        end
    end
    
    def destroy
        @medicament=Medicament.find(params[:id])
        @medicament.destroy
        flash[:success] = "Лекот е избришан."
         redirect_to medicaments_path
    end
    
    private
    
    def medicament_params
        params.require(:medicament).permit(:ime_lek, :komentar, :producer_id, :generic_name_id)
    end
    
    def require_admin
      if current_user.admin != true
        flash[:danger] = "Промена може да направи само администратор"
        redirect_to medicaments_path
      end
    end
end

app/views/medicaments/edit.html.erb
<%= render 'shared/page_title', title: "Додај нова група" %> 
<%= render 'shared/errors', obj: @medicament %>

<div class="row">
    <div class="well col-md-8 col-md-offset-2">
        <%= form_for @medicament do |f| %>
        <%= f.label :Име_на_лек %>
        <%= f.text_field :ime_lek %>
        
        <strong>Производител:</strong>
        
        <%= f.collection_select(:producer_id, Producer.all, :id, :ime_proizvoditel, {:include_blank => ''}) %>
        
        <strong>Генеричко име:</strong>
        
        <%= f.collection_select(:generic_name_id, GenericName.all, :id, :genericko_ime, {:include_blank => ''}) %>
        <%= f.label :Својства %>
        <%= f.text_field :komentar %>

        <%= f.submit 'Измени', class: "btn btn-success" %>
        <% end %>
    </div>
</div>

app/views/medicaments/index.html.erb
<%= render 'shared/page_title', title: "Сите регистрирани лекови" %>

<%= will_paginate %>
<% @medicaments.each do |med| %>
    <div class="row">
        <div class="col-lg-12 well">
            <section class="chef_info center">
               <h3> <%= link_to med.ime_lek, medicament_path(med) %></h3>
            </section>
        </div>
    </div>
    <hr/>
<% end %>
<%= will_paginate %>

app/views/medicaments/new.html.erb
<%= render 'shared/page_title', title: "Додај нова група" %> 
<%= render 'shared/errors', obj: @medicament %>

<div class="row">
    <div class="well col-md-8 col-md-offset-2">
        <%= form_for @medicament do |f| %>
        <%= f.label :"Име на лек:" %>
        <%= f.text_field :ime_lek, :size => "40" %>
        </br></br>
        <strong>Производител:</strong>
        
        <%= f.collection_select(:producer_id, Producer.all, :id, :ime_proizvoditel, {:include_blank => ''}) %>
        </br></br>
        <strong>Генеричко име:</strong>
        
        <%= f.collection_select(:generic_name_id, GenericName.all, :id, :genericko_ime, {:include_blank => ''}) %>
        </br></br>
        <%= f.label :"Својства:" %>
        <%= f.text_field :komentar, :size => "40" %>
        
        </br></br>
        <%= f.submit 'Креирај', class: "btn btn-success pull-right" %>
        <% end %>
    </div>
</div>

app/views/medicaments/show.html.erb
<%= render 'shared/errors', obj: @commentt %>
<%= render 'shared/page_title', title: "Лек" %>
<div class="col-lg-12 well">
    <section class="group_info center">
        <strong> <h3><%= @medicament.ime_lek %></h3> </strong>
        <h4>Овој лек има генеричко име <%= @medicament.generic_name.genericko_ime %></h4>
<<<<<<< HEAD
        <h4><u>Производител:</u> <%= link_to @medicament.producer.ime_proizvoditel, producer_path(@medicament.producer) %> , <%= @medicament.producer.poteklo %> </h4>
=======
        <h4><u>Производител:</u> <%= link_to @medicament.producer.ime_proizvoditel, producer_path(@medicament.producer) %>, <%= @medicament.producer.poteklo %> </h4>
>>>>>>> fixed navbar
        <% if @medicament.komentar.present? %>
            <h4><%= @medicament.komentar %></h4>
        <% end %>
        <% if @kommeds.any? %>
            <%= render 'reviewmeds/reviewmed', obj: @kommeds %>
        <% end %>
        <% if logged_in? %>
        <div class="col-lg-12 well">
            <%= form_for([@medicament, @commentt]) do |c| %>
              <%= c.label "Додади коментар:" %>
              <%= c.text_area :komentar_na_lek %>
              <%= c.submit "Коментирај" %>
            <% end %>
        </div>
        <% end %>
        <% if logged_in? && (current_user.admin) %>
            <div class="col-md-12 well">
                <button class="btn pull-left"><%= link_to "Додај нов лек", new_medicament_path %></button>
                <button class="btn pull-right btn-danger"><%= link_to "Избриши лек", @medicament, method: :delete, data: {confirm: "Дали сте сигурни дека сакате да го избришете овој лек?"} %></button>
                <button class="btn pull-right"><%= link_to "Измени", edit_medicament_path(@medicament.id) %></button>
            </div>
        <% end %>
    </section>
</div>
        
        
        
    <hr/>